# Generated by Django 4.0.6 on 2022-09-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entity',
            table='entities',
        ),
    ]
